baseURL = 'https://your-blog-url.netlify.app/'
languageCode = 'en-us'
title = 'My Personal Blog'
theme = 'ananke'

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Welcome to my personal blog"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/
  background_color_class = "bg-black"
  recent_posts_number = 3

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
