baseURL = '/'
languageCode = 'en-us'
title = 'My Personal Blog'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[build]
  writeStats = true

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "node_modules"
    target = "assets/node_modules"

[params]
  env = "production"
  title = "My Personal Blog"
  description = "Welcome to my personal blog"
  keywords = ["Blog", "Portfolio", "PaperMod"]
  author = "Your Name"
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true

  [params.homeInfoParams]
  Title = "Welcome to My Blog 👋"
  Content = """
Welcome to my personal blog! Here I share my thoughts and experiences.
"""

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/yourusername"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^VERCEL_']
