baseURL = '/'
languageCode = 'en-us'
title = 'My Personal Blog'
theme = 'ananke'

[build]
  writeStats = true

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "node_modules"
    target = "assets/node_modules"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Welcome to my personal blog"
  background_color_class = "bg-black"
  recent_posts_number = 3

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^VERCEL_']
